language: r
r:
  - oldrel
  - release
  - devel

sudo: required

cache: packages

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
    - jimhester/covr
    - parksandwlidlife/wastdr

r_packages:
  - covr

after_success:
    - Rscript -e 'library(covr);codecov()'
