language: r
r:
  - oldrel
  - release
  - devel

sudo: false

cache: packages

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

env: _R_CHECK_CRAN_INCOMING_=FALSE

before_install:
  - sudo apt-get -y install libproj-dev libgdal-dev

r_github_packages:
    - jimhester/covr

r_packages:
  - covr

after_success:
    - Rscript -e 'library(covr);codecov()'
