---
title: "Producing insight from WAStD"
author: "Florian Mayer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(wastdr)
library(dplyr)
library(magrittr)
library(leaflet)
library(lubridate)
library(listviewer)
library(DT)
library(ggplot2)
```

# Load data
```{r, echo=T}
filter_2017 <- . %>% dplyr::filter(date > dmy("17/11/2017"))
filter_west_pilbara <- . %>% dplyr::filter(
    longitude > 117.0,
    longitude < 117.3,
    latitude <  -20.5,
    latitude >  -20.7
)

if (file.exists("~/tracks.Rda")){
    load("~/tracks.Rda")
} else {
    track_records <- wastdr::get_wastd("turtle-nest-encounters")
    # listviewer::jsonedit(utils::head(track_records$content))
    tracks <- parse_turtle_nest_encounters(track_records) 
    save(tracks, file = "~/tracks.Rda")
}
```

# Filter data
To filter records to one area, we can either filter by area or site ID 
(once enabled), or simply filter by a bounding box.

In this example, we'll filter to an area surveyed by the West Pilbara Turtle 
Program.

```{r}
tracks_wp <- tracks %>% filter_2017 %>% filter_west_pilbara
DT::datatable(tracks_wp)
save(tracks_wp, file = "~/tracks_wp.Rda")
```


# Map

```{r, eval=T}
#' makeAwesomeIcon factory
mkicon <- function(ico, col) leaflet::makeAwesomeIcon(icon = ico, markerColor = col)

trackIcons <- awesomeIconList(
  "cheloniidae-fam" = mkicon('align-center', 'black'),
  "chelonia-mydas" = mkicon('align-center', 'green'),
  "eretmochelys-imbricata" = mkicon('align-center', 'blue'),
  "natator-depressus" = mkicon('align-center', 'red'),
  "corolla-corolla" = mkicon('align-center', 'yellow'),
  "lepidochelys-olivacea" = mkicon('align-center', 'green'),
  "caretta-caretta" = mkicon('align-center', 'brown')
  )

tagIcons <- awesomeIconList(
  "cheloniidae-fam" = mkicon('tag', 'black'),
  "chelonia-mydas" = mkicon('tag', 'green'),
  "eretmochelys-imbricata" = mkicon('tag', 'blue'),
  "natator-depressus" = mkicon('tag', 'red'),
  "corolla-corolla" = mkicon('tag', 'yellow'),
  "lepidochelys-olivacea" = mkicon('tag', 'green'),
  "caretta-caretta" = mkicon('tag', 'brown')
  )

nestIcons <- awesomeIconList(
  "cheloniidae-fam" = mkicon('baby-formula', 'black'),
  "chelonia-mydas" = mkicon('baby-formula', 'green'),
  "eretmochelys-imbricata" = mkicon('baby-formula', 'blue'),
  "natator-depressus" = mkicon('baby-formula', 'red'),
  "corolla-corolla" = mkicon('baby-formula', 'yellow'),
  "lepidochelys-olivacea" = mkicon('baby-formula', 'green'),
  "caretta-caretta" = mkicon('baby-formula', 'brown')
  )

leaflet(tracks_wp, width=800, height=600) %>% 
  addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  addProviderTiles("OpenStreetMap.Mapnik", group = "Place names") %>%
  setView(lng=117.15, lat=-20.6, zoom=14) %>%
  addAwesomeMarkers(~longitude, ~latitude,
                    data=tracks_wp, 
                    icon = ~trackIcons[species],
                    label = ~paste("Track", date, nest_age, species, nest_type),
                    popup = ~paste("Track", date, nest_age, species, nest_type),
                    group = "Tracks") %>%
  addLayersControl(baseGroups = c("Aerial", "Place names"),
                   overlayGroups = c("Tracks"))
```
