#' @description \code{\link{wastdr}} is an R Client for the ODK Central API.
#' The 'WA Sea Turtle Database' 'WAStD' is a 'Django' web app with a 'RESTful'
#' 'API' returning 'GeoJSON' 'FeatureCollections'.
#' \code{\link{wastdr}} provides helpers to retrieve data from the 'API',
#' and to turn the received 'GeoJSON' into R 'tibbles'.
#' \code{\link{wastdr}} will grow alongside implemented
#' use cases of retrieving and analysing 'WAStD' data.
#'
#'   Please see the `wastdr` website for full documentation:
#'   * <https://dbca-wa.github.io/wastdr/>
#'
#'   `ruODK` is "pipe-friendly" and re-exports `%>%`, but does not
#'   require their use.
#'
#' @keywords internal
"_PACKAGE"


# Silence R CMD CHECK warning: Use lifecycle somewhere in package
lifecycle::deprecate_soft

# CMD check silencer
utils::globalVariables(
  c(
    ".",
    "absolute_admin_url",
    "aes",
    "area_name",
    "area_type",
    "calendar_date_awst",
    "change_url",
    "datetime",
    "days",
    "desc",
    "details_nest_age",
    "details_nest_type",
    "details_species",
    "disturbance",
    "dist_extra",
    "dist_prod",
    "disturbance_cause",
    "disturbanceobservation_disturbance_cause",
    "duration_hours",
    "duration_minutes",
    "encounter_type",
    "encounter_when",
    "encounter_encounter_type",
    "end_comments",
    "end_time",
    "egg_count",
    "egg_count_calculated",
    "eggs_counted",
    "emergence_success",
    "encounter_area_name",
    "encounter_site_name",
    "existing_tsc_tne",
    "fan_angles_measured",
    "first_day",
    "health",
    "hours_surveyed",
    "hatching_success",
    "habitat",
    "hatchlings_measured",
    "id",
    "is_production",
    "iso_week",
    "layersControlOptions",
    "last_day",
    "logger_found",
    "markerClusterOptions",
    "mwi_dmg_prod",
    "mwi_extra",
    "mwi_prod",
    "mwi_tag_prod",
    "n",
    "name",
    "nest_age",
    "nest_disturbance",
    "nest_eggs_counted",
    "nest_fan_angles_measured",
    "nest_habitat",
    "nest_hatchlings_measured",
    "nest_logger_found",
    "nest_nest_tagged",
    "nest_tagged",
    "nest_type",
    "odkc_data",
    "obs",
    "observation_start_time",
    "pk",
    "properties",
    "reporter",
    "season",
    "season_week",
    "site_id",
    "site_name",
    "species",
    "status_health",
    "start",
    "start_comments",
    "start_time",
    "status",
    "source_id",
    "successful",
    "surveys",
    "sve_extra",
    "sve_prod",
    "svs_extra",
    "svs_prod",
    "tracks_dist_extra",
    "tracks_dist_prod",
    "tracks_egg_prod",
    "tracks_extra",
    "tracks_fan_outlier_prod",
    "tracks_hatch_prod",
    "tracks_log_prod",
    "tracks_prod",
    "turtle_date",
    "user_mapping",
    "value",
    "vars",
    "wastd_data",
    "when",
    "Year",
    "...1",
    "...2",
    "...3",
    "...4",
    "acc",
    "alt",
    "aspect",
    "body_part",
    "corrected_date",
    "datum_code",
    "description",
    "display_observation",
    "egg_count_method",
    "egg_count_no_dead_hatchlings",
    "egg_count_no_depredated_eggs",
    "egg_count_no_egg_shells",
    "egg_count_no_live_hatchlings",
    "egg_count_no_undeveloped_eggs",
    "egg_count_no_unhatched_eggs",
    "egg_count_no_unhatched_term",
    "email",
    "first_name",
    "flipper",
    "identification_type",
    "lat",
    "latitude",
    "location_code",
    "lon",
    "longitude",
    "measurement_type",
    "measurement_units",
    "nesting",
    "new_code",
    "o_date",
    "o_time",
    "observation_date",
    "observation_date_old",
    "observation_datetime_gmt08",
    "observation_datetime_utc",
    "observation_time",
    "other_tag_id",
    "overview_location",
    "place_code",
    "place_name",
    "rookery",
    "side",
    "site_latitude",
    "site_longitude",
    "surname",
    "tag_id",
    "tag_name",
    "tsc_data",
    "aliases",
    "details_observed_at_accuracy",
    "dist",
    "geometry",
    "nickname",
    "observer",
    "odkc_prep",
    "odkc_username",
    "username",
    "atkn", "aurl", "checks_checked_for_flipper_tags", "checks_checked_for_injuries",
    "checks_scanned_for_pit_tags", "death_cause_of_death",
    "death_cause_of_death_confidence", "details_maturity", "details_sex",
    "details_taxon", "handler", "incident_habitat", "incident_incident_time",
    "incident_observed_at_accuracy", "incident_observed_at_manual_accuracy",
    "morphometrics_curved_carapace_length_accuracy",
    "morphometrics_curved_carapace_length_mm",
    "morphometrics_curved_carapace_width_accuracy",
    "morphometrics_curved_carapace_width_mm",
    "morphometrics_maximum_head_width_accuracy",
    "morphometrics_maximum_head_width_mm",
    "morphometrics_tail_length_carapace_accuracy",
    "morphometrics_tail_length_carapace_mm", "odkc_ex", "odkc_tf", "odkc_up",
    "recorder", "status_activity", "status_behaviour", "tsc_users", "updt", "vbse",
    "nest_tag_date_nest_laid",
    "nest_tag_flipper_tag_id",
    "nest_tag_status",
    "nest_tag_tag_comments",
    "nest_tag_tag_label",
    "body_weight_g", "comments", "disturbance_cause_confidence",
    "disturbance_severity", "egg_count_nest_depth_bottom",
    "egg_count_nest_depth_top", "straight_carapace_length_mm",
    "straight_carapace_width_mm",
    "emergence_climate_cloud_cover_at_emergence",
    "fan_angles_bearing_to_water_manual",
    "fan_angles_hatchling_emergence_time_known",
    "fan_angles_leftmost_track_manual",
    "fan_angles_light_sources_present",
    "fan_angles_no_tracks_main_group",
    "fan_angles_no_tracks_main_group_max",
    "fan_angles_no_tracks_main_group_min",
    "fan_angles_outlier_tracks_present",
    "fan_angles_path_to_sea_comments",
    "fan_angles_rightmost_track_manual",
    "hatchling_emergence_time_group_hatchling_emergence_time",
    "hatchling_emergence_time_group_hatchling_emergence_time_source",
    "bearing_outlier_track_degrees",
    "outlier_group_size",
    "outlier_track_comment",
    "encounter_activity",
    "encounter_maturity",
    "encounter_observed_at_accuracy",
    "encounter_sex",
    "encounter_species",
    "light_bearing_manual",
    "light_source_description",
    "light_source_type",
    "odkc_mwi_tag_as_wastd_tagobs",
    "outlier_track_bearing_manual",
    "damage_age",
    "damage_type",
    "disturbanceobservation_comments",
    "disturbanceobservation_disturbance_cause_confidence",
    "disturbanceobservation_location_accuracy",
    "logger_id",
    "odkc_un_trim",
    "tag_comments",
    "tag_location",
    "tag_status",
    "tag_type",
    "transect",
    "tx",
    "wastd_users"
  )
)
