on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # See https://github.com/actions/virtual-environments
          - { os: windows-latest, r: "devel" } # windows-2019
          - { os: windows-latest, r: "release" }
          # - { os: windows-latest, r: "oldrel" } # fails to install drake
          - { os: windows-2016, r: "devel" }
          - { os: windows-2016, r: "release" }
          # - { os: windows-2016, r: "oldrel" } # fails to install drake
          - { os: macOS-latest, r: "devel" } # macos-10.15
          - { os: macOS-latest, r: "release"}
          - { os: macOS-latest, r: "oldrel"}
          # - { os: ubuntu-20.04, r: "devel" } # # not released yet
          # - { os: ubuntu-20.04, r: "release"} # not released yet
          # - { os: ubuntu-20.04, r: "oldrel" } # not released yet
          # - { os: ubuntu-latest, r: "devel" } # fails setup-r
          - { os: ubuntu-latest, r: "release", pkgdown: "true"} # ubuntu-18.04
          - { os: ubuntu-latest, r: "oldrel" }
          # - { os: ubuntu-16.04, r: "devel" } # fails setup-r
          - { os: ubuntu-16.04, r: "release"} # fails setup-r
          - { os: ubuntu-16.04, r: "oldrel" } # fails setup-r
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      ODKC_URL: ${{secrets.ODKC_URL}}
      ODKC_UN: ${{secrets.ODKC_UN}}
      ODKC_PW: ${{secrets.ODKC_PW}}
      WASTDR_API_URL: ${{secrets.WASTDR_API_URL}}
      WASTDR_API_UN: ${{secrets.WASTDR_API_UN}}
      WASTDR_API_PW: ${{secrets.WASTDR_API_PW}}
      WASTDR_API_TOKEN: ${{secrets.WASTDR_API_TOKEN}}
      GITHUB_PAT: ${{secrets.GITHUB_PAT}}
      WASTDR_SKIP_SLOW_TESTS: ${{ secrets.WASTDR_SKIP_SLOW_TESTS }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install R packages for CI
        run: |
          install.packages('remotes')
          remotes::install_github('r-hub/sysreqs')
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Hoard toilet paper (and R packages)
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      # sf needs GDAL > 2.0.1, stringr needs libicu-dev
      - name: Add Ubuntu Xenial patches
        if: matrix.config.os == 'ubuntu-16.04'
        run: |
          sudo add-apt-repository -y ppa:opencpu/jq
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update

      - name: Add Ubuntu patches
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev libicu-dev

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Bash Windows over the head with a source install of dplyr and sf
        if: runner.os == 'Windows'
        run: |
          install.packages("dplyr", type = "source")
          install.packages("sf", type = "source")
        shell: Rscript {0}

      - name: Source install macOS system deps
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install udunits
          brew install proj
          brew install gdal
          brew install libxml2
          brew install v8

      # macos-latest configure: error: libproj not found in standard or given locations.
      - name: Source install macOS packages
        if: runner.os == 'macOS'
        run: |
          remotes::install_github('ropensci/geojsonio')
          remotes::install_github('hrbrmstr/ggalt')
          remotes::install_github('r-spatial/sf')
        shell: Rscript {0}

      - name: Source install Ubuntu Xenial R packages
        if: matrix.config.os == 'ubuntu-16.04'
        run: |
          install.packages(c('knitr', 'roxygen2', 'stringi', 'stringr', 'sf'))
        shell: Rscript {0}

      - name: Install R dependencies
        run: |
          install.packages('V8')
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: R CMD Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Report test coverage
        if: matrix.config.os == 'ubuntu-18.04' && matrix.config.r == '3.6'
        run: covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}

      - name: Setup git and install package
        if: matrix.config.os == 'ubuntu-18.04' && matrix.config.r == '3.6'
        run: |
          git config --global user.name ${{secrets.GH_USER}}
          git config --global user.email ${{secrets.GH_EMAIL}}
          R CMD INSTALL .

      - name: Deploy pkgdown docs
        if: matrix.config.os == 'ubuntu-18.04' && matrix.config.r == '3.6'
        run: |
          remotes::install_dev("pkgdown")
          pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
